# Generated by Django 5.2.15 on 2026-06-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='dealer_code',
        ),
    ]
